// import { signIn, signOut, useSession } from "next-auth/react";
// import Head from "next/head";
// import Link from "next/link";

// import { api } from "~/utils/api";

// export default function Home() {
//   const hello = api.post.hello.useQuery({ text: "from tRPC" });

//   return (
//     <>
//       <Head>
//         <title>Create T3 App</title>
//         <meta name="description" content="Generated by create-t3-app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
//         <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
//           <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
//             Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
//           </h1>
//           <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
//             <Link
//               className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
//               href="https://create.t3.gg/en/usage/first-steps"
//               target="_blank"
//             >
//               <h3 className="text-2xl font-bold">First Steps →</h3>
//               <div className="text-lg">
//                 Just the basics - Everything you need to know to set up your
//                 database and authentication.
//               </div>
//             </Link>
//             <Link
//               className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
//               href="https://create.t3.gg/en/introduction"
//               target="_blank"
//             >
//               <h3 className="text-2xl font-bold">Documentation →</h3>
//               <div className="text-lg">
//                 Learn more about Create T3 App, the libraries it uses, and how
//                 to deploy it.
//               </div>
//             </Link>
//           </div>
//           <div className="flex flex-col items-center gap-2">
//             <p className="text-2xl text-white">
//               {hello.data ? hello.data.greeting : "Loading tRPC query..."}
//             </p>
//             <AuthShowcase />
//           </div>
//         </div>
//       </main>
//     </>
//   );
// }

// function AuthShowcase() {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.post.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// }
import Link from "next/link";
import Header from "~/components/Header";
import Carousel from "~/components/Carousel";
import Tutorial from "~/components/Tutorial";
import Collection from "~/components/Collection";

export default function Home(){
  return (
    <div className="pt-28">
      <div className="fixed z-50 top-0"><Header /></div>
      <div className="ml-4 text-2xl font-bold">Trending events</div>
      <div className="w-full mt-5">
        <Carousel 
        // img={[
        // "https://www.cnet.com/a/img/resize/20d6844768bd3f5f0df41deee97897423bcaf3c5/hub/2021/11/03/3c2a7d79-770e-4cfa-9847-66b3901fb5d7/c09.jpg?auto=webp&fit=crop&height=1200&width=1200",
        // "https://community-lens.storage.googleapis.com/preview-media/thumbnail_poster/a8892413-3bec-4f3d-b4ef-02e56cc540bc.jpg",
        // "https://m.media-amazon.com/images/I/31GEsNVK8dL._AC_UF1000,1000_QL80_.jpg",
        // "https://m.media-amazon.com/images/I/51XISp6ViuL._AC_UF894,1000_QL80_.jpg",
        // "https://i.chzbgr.com/full/9743959040/h39973DB8/dog-inside-now-my-dog",
        // "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZDp6C_WCdCnXGwObacXyxQNpLtxf1eMZxuA&usqp=CAU"
        // ]}
        img={[
        "https://www.cnet.com/a/img/resize/20d6844768bd3f5f0df41deee97897423bcaf3c5/hub/2021/11/03/3c2a7d79-770e-4cfa-9847-66b3901fb5d7/c09.jpg?auto=webp&fit=crop&height=1200&width=1200",
        "https://community-lens.storage.googleapis.com/preview-media/thumbnail_poster/a8892413-3bec-4f3d-b4ef-02e56cc540bc.jpg",
        "https://m.media-amazon.com/images/I/31GEsNVK8dL._AC_UF1000,1000_QL80_.jpg",
        "https://m.media-amazon.com/images/I/51XISp6ViuL._AC_UF894,1000_QL80_.jpg",
        "https://i.chzbgr.com/full/9743959040/h39973DB8/dog-inside-now-my-dog",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZDp6C_WCdCnXGwObacXyxQNpLtxf1eMZxuA&usqp=CAU",
        "https://m.media-amazon.com/images/I/31GEsNVK8dL._AC_UF1000,1000_QL80_.jpg",
        "https://www.cnet.com/a/img/resize/20d6844768bd3f5f0df41deee97897423bcaf3c5/hub/2021/11/03/3c2a7d79-770e-4cfa-9847-66b3901fb5d7/c09.jpg?auto=webp&fit=crop&height=1200&width=1200",
        ]}
        />
      </div>
      {/* <div className="ml-4 text-2xl font-bold">Ongoing events</div>
      <div className="w-full mt-5">
        <Collection img={[
        "https://www.cnet.com/a/img/resize/20d6844768bd3f5f0df41deee97897423bcaf3c5/hub/2021/11/03/3c2a7d79-770e-4cfa-9847-66b3901fb5d7/c09.jpg?auto=webp&fit=crop&height=1200&width=1200",
        "https://community-lens.storage.googleapis.com/preview-media/thumbnail_poster/a8892413-3bec-4f3d-b4ef-02e56cc540bc.jpg",
        "https://m.media-amazon.com/images/I/31GEsNVK8dL._AC_UF1000,1000_QL80_.jpg",
        "https://m.media-amazon.com/images/I/51XISp6ViuL._AC_UF894,1000_QL80_.jpg",
        "https://i.chzbgr.com/full/9743959040/h39973DB8/dog-inside-now-my-dog",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZDp6C_WCdCnXGwObacXyxQNpLtxf1eMZxuA&usqp=CAU"
      ]} />
      </div> */}
      <div className="w-full mt-8 bg-base-200">
        <Tutorial />
      </div>
    </div>
  )
}