import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import Header from "~/components/Header";
import { AnimateOnScroll } from "~/utils/hooks/VisibilityHook";
import { api } from "~/utils/api";
import Carousel from "~/components/Carousel";
import Tutorial from "~/components/Tutorial";
import Footer from "~/components/Footer";
export default function Home() {
  return (
    <>
      <Head>
        <title>💡🎰 Bulbbet</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center">
        <Header />
        <div className="pt-16">
          <Hero />
        </div>
        <div className="w-full ">
          <TrendingEvent />
        </div>
        <div className="w-full items-center justify-center pt-10">
          <div className="bg-base-200">
            <Tutorial />
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}

const TrendingEvent = () => {
  const { data } = api.event.getTrending.useQuery(undefined);
  return (
    <>
      <div className="flex w-full justify-between px-5 text-4xl font-bold md:px-12">
        <div className="">📈 Trending events</div>
        <Link href="/collection">
          <div className="btn btn-primary">View all</div>
        </Link>
      </div>
      <div className="w-full pt-5">
        <div className="hide-scroll mx-5 overflow-scroll rounded-lg bg-neutral py-10 md:mx-10">
          {data && <Carousel trendingData={data} />}
        </div>
      </div>
    </>
  );
};

const generate4RandomUniqueEmoji = (emoji_list: string[]) => {
  const emoji: string[] = [];
  while (emoji.length < 4) {
    const randomEmoji =
      emoji_list[Math.floor(Math.random() * emoji_list.length)] ?? "";
    if (!emoji.includes(randomEmoji)) {
      emoji.push(randomEmoji);
    }
  }
  return emoji;
};

const Hero = () => {
  const [emoji, setEmoji] = useState<string[]>([]);
  const emoji_list = [
    "🎲",
    "🎰",
    "🏇",
    "🎫",
    "💹",
    "💰",
    "💸",
    "💡",
    "💡",
    "💡",
    "💡",
    "🪀",
    "🃏",
    "🤞",
    "💵",
    "🥇",
    "🍻",
    "⚽️",
  ];
  useEffect(() => {
    setEmoji(generate4RandomUniqueEmoji(emoji_list));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return (
    <div className="hero h-screen w-full select-none">
      <div className="hero-content text-center">
        <div className="relative max-w-md py-0 lg:py-10">
          <AnimateOnScroll reappear={true}>
            <h1 className="items-center justify-center text-5xl sm:text-7xl">
              Bet on
              <span className="block h-[calc(theme(fontSize.5xl)*theme(lineHeight.tight))] flex-col overflow-hidden text-secondary-focus md:h-[calc(theme(fontSize.7xl)*theme(lineHeight.tight))]">
                <ul className="block animate-text-slide text-center leading-tight [&_li]:block">
                  <li>
                    Futures
                    <div className="inline align-middle text-4xl sm:text-6xl">
                      ⏳
                    </div>
                  </li>
                  <li>
                    Grades
                    <div className="inline text-error">{"🇫"}</div>
                  </li>
                  <li>
                    Events
                    <div className="inline align-middle text-4xl sm:text-6xl">
                      📅
                    </div>
                  </li>
                  <li>
                    Predictions
                    <div className="inline align-middle text-4xl sm:text-6xl">
                      🔮
                    </div>
                  </li>
                  <li>
                    Trends
                    <div className="inline align-middle text-4xl sm:text-6xl">
                      📈
                    </div>
                  </li>
                  <li aria-hidden="true">
                    Futures
                    <div className="inline align-middle text-4xl sm:text-6xl">
                      ⏳
                    </div>
                  </li>
                </ul>
              </span>
              with
            </h1>
          </AnimateOnScroll>
          <h1 className="inline whitespace-nowrap text-6xl font-bold sm:text-8xl">
            Bulbbet
          </h1>

          <AnimateOnScroll
            reappear={true}
            className="absolute -top-14 right-2 text-7xl sm:-right-16 sm:-top-28 lg:-right-32 lg:-top-20 lg:text-9xl"
            classNameOnEnd="rotate-12"
          >
            {/* top right */}
            {emoji[0]}
          </AnimateOnScroll>
          <AnimateOnScroll
            reappear={true}
            className="absolute -top-14 left-2 text-7xl sm:-left-10 sm:-top-28 lg:-left-20 lg:-top-20 lg:text-9xl"
            classNameOnEnd="-rotate-[12deg]"
          >
            {/* top left */}
            {emoji[1]}
          </AnimateOnScroll>
          <AnimateOnScroll
            reappear={true}
            className="absolute -bottom-24 -left-0 hidden rotate-12 text-7xl sm:-bottom-24 sm:-left-5 lg:-left-52 lg:top-1/2 lg:-mt-16 lg:flex lg:text-9xl"
            classNameOnStart="rotate-[10deg]"
            classNameOnEnd="-rotate-[10deg]"
          >
            {/* bottom left or mid left */}
            {emoji[2]}
          </AnimateOnScroll>
          <AnimateOnScroll
            reappear={true}
            className="absolute -bottom-24 -right-0 hidden rotate-12 text-7xl sm:-bottom-24 sm:-right-5 lg:-right-52 lg:top-1/2 lg:-mt-16 lg:flex lg:text-9xl"
            classNameOnStart="-rotate-[10deg]"
            classNameOnEnd="rotate-[10deg]"
          >
            {/* bottom right or mid right */}
            {emoji[3]}
          </AnimateOnScroll>
          <p className="py-6 text-3xl">Put your 💡 where your mouth is</p>
          {/* </AnimateOnScroll> */}
          {/* <button className="btn btn-primary">Install Our App</button> */}
        </div>
      </div>
    </div>
    // </div>
  );
};
